config/routes.rb
Yanivemperorapp::Application.routes.draw do

  root to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'

end

app/models/article.rb
class Article < ActiveRecord::Base

	attr_accessible :title, :description
	validates :title, presence: true, length: { minimum: 3, maximun: 50 }
	validates :description, presence: true, length: { minimum: 10, maximun: 300 }

end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def home
	end

	def about
	end	


end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<div id="Yaniv new About Page">
    <h1>This app recognizes Yaniv, the best emperor in the universe</h1>
    <h1>First draft: 11 January 2018</h1>    
</div> 
<%= link_to 'Home Page', root_path%>   

app/views/welcome/home.html.erb
<div id="Yaniv new Homepage">
    <h1>Getting started</h1>
    <h2>Here&rsquo;s how to start ruling:</h2>
    <div id="page">
        <ol>
            <li>
              <h2>Use <code>rails generate</code> to create your models and controllers</h2>
              <p>To see all available options, run it without parameters.</p>
            </li>

            <li>
              <h2>Set up a default route and remove <span class="filename">public/index.html</span></h2>
              <p>Routes are set up in <span class="filename">config/routes.rb</span>.</p>
            </li>

            <li>
              <h2>Create your database</h2>
              <p>Run <code>rake db:create</code> to create your database. If you're not using SQLite (the default), edit <span class="filename">config/database.yml</span> with your username and password.</p>
            </li>

            <li>
              <h2>?</h2>
              <p>unsolicited details on the invasion plan.</p>
            </li>

            <li>
              <h2>TAKE OVER THE WORLD!</h2>
              <p>All hail emperor Yaniv</p>
            </li>
    	</ol>
    </div>
</div>

<%= link_to 'About Page', welcome_about_path %>     